# -*- coding: utf-8 -*-
"""In-som-concrete

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dv1zYah4k9vEYpebO8Ewo2GhiB38ibOH
"""

!pip install minisom

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#http://archive.ics.uci.edu/ml/datasets/Concrete+Compressive+Strength
df = pd.read_excel('Concrete_Data.xls')

df

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(df)
input_data_scaled = scaler.transform(df)

input_data_scaled

from minisom import MiniSom
som = MiniSom(x= 13, y= 13, input_len= 9, sigma= 1.0, learning_rate= 0.5, random_seed=0)

som.random_weights_init(input_data_scaled)

som.train_random(data = input_data_scaled, num_iteration= 100)

graph = som.distance_map()

f, ax = plt.subplots(figsize=(10, 10))
sns.heatmap(graph, annot=True, linewidths=0, ax=ax, square=True, cmap='jet')

"""
f, ax = plt.subplots(figsize=(10, 10))
graph_matrix_100 = sns.heatmap(graph, annot=False, linewidths=0, ax=ax, square=True, cmap='cividis')
graph_matrix_100 = graph_matrix_100.get_figure()
graph_matrix_100.savefig(fname= "grafico-calor.png", format= "png", dpi= 1080)
"""

sns.clustermap(graph, cmap = 'jet')